### ISSUE TITLE
Release Plan 2.4.0

### ISSUE THREAD

**Issue by pan3793** [housepower/ClickHouse-Native-JDBC#197]
Estimated Release Date 
===============
Mid Nov 2020

Highlight
======
- We are gonna switch to [semantic versioning](https://semver.org/), so the next release version will be 2.4.0, and the bug fix version would be available quickly.

- We introduce a new module `clickhouse-integration-spark` base on Spark Jdbc DataSource API for integrating with Spark, check detail at [README](https://github.com/housepower/ClickHouse-Native-JDBC#integration-with-spark)

- In the past few weeks, we were more focus on code quality, fixed all [LGTM](https://lgtm.com/projects/g/housepower/ClickHouse-Native-JDBC/alerts/) alerts and got A+ score.

Changelog
=======
- [x] Implement `clickhouse-integration-spark` base on Spark Jdbc DataSource API (#170 #184)
- [x] Batch insert support nullable types in arrays and nested types (#144 #194)
- [x] Support Boolean (#196)
- [x] Fix timezone issue (#195)
- [x] Fix potential concurrence issue (#191)
- [x] Code refactor, fixed all [LGTM](https://lgtm.com/projects/g/housepower/ClickHouse-Native-JDBC/alerts/) alerts and got A+ score.
- [x] Refactor `ClickHouseStatement` inheritance tree (#201)
- [x] Migrate to mockito3 (#175)
- [x] Migrate to org.lz4:lz4-java (#174)
- [x] Migrate to Junit5 (#171)
- [x] Bump yandex/clickhouse-jdbc 0.2.4
- [x] Bump jmh 1.26
- [x] Enable checkstyle (#172)
- [x] Enable code coverage (#190)
- [x] Improve Docs and Readme
- [x] Add missing license headers
