### ISSUE TITLE
Release Plan 2.5.0

### ISSUE THREAD

**Issue by pan3793** [housepower/ClickHouse-Native-JDBC#272]
Estimated Release Date 
===
Late Dec 2020

Highlight
===
- The project static website is available at [Home Page](https://housepower.github.io/ClickHouse-Native-JDBC)
- The China mirror repo is available at [Gitee](https://gitee.com/housepower/ClickHouse-Native-JDBC)
- Implemented `BalancedClickhouseDataSource` to support connect to clickhouse cluster
- Now the JDBC driver works with DataGrip and DBeaver
- Introduced a log facade which prefer to bind `slf4j` if it exists in classpath, otherwise fallback to JDK `Logger`, and added logs for tracing, debugging and warning. 

This release contains lots of internal refactors, and currently, this driver guarantee none stable API except JDBC API itself, please be careful if you use the internal API which not belongs to JDBC standard interfaces.

Changelog
===
- [x] (feature) Implement `BalancedClickhouseDataSource` to support multi instances (#205)
- [x] (bugfix) Fix invalid package clickhouse-integration-spark_2.12 (#206)
- [x] (feature) Implement `ClickHouseConnection` catalog and schema method (#208)
- [x] (enhance) Enhance `Number` process
- [x] (build) Disable deploy `examples` module
- [x] (test) Integration tests with connection pool (#212)
- [x] (feature) Support `charset` parameter (#213)
- [x] (feature) Implement `ClickHousePreparedStatment` `#setBytes` and `#getBytes` (#213)
- [x] (enhance) Trim space before parsing SQL
- [x] (feature) Support `tcp_keep_alive` parameter
- [x] (bugfix) Fix DateTime64 nanos and scale (#217)
- [x] (bugfix) Reset connection `STATE` when recreate connection (#221)
- [x] (bugfix) Skip remaining response when ping (#224)
- [x] (refactor) Decouple `RequestOrResponse` and rename `PhysicalConnection` to `NativeClient` (#225)
- [x] (feature) Introduce log classes to avoid hard dependence on `slf4j` (#231)
- [x] (build) Add `debug` Maven profile (#235)
- [x] (enhance) Add LRU cache for lexer `IDataType` (#236)
- [x] (feature) Refactor and implement ClickHouseDatabaseMetadata (#233)
- [x] (feature) Support type alias (#240)
- [x] (bugfix) Explicit upcast ByteBuffer to Buffer (#243)
- [x] (deps) Bump ini from 1.3.5 to 1.3.8 (#250)
- [x] (feature) Support Decimal256 && Decimal128 (#239)
- [x] (refactor) Refactor and fixup (#246)
- [x] (deps) bump alibaba druid 1.2.4
- [x] (deps) bump slf4j 1.7.30
- [x] (deps) bump mockito 3.6.28
- [x] (deps) bump jmh 1.27
- [x] (bugfix) Cast correctly numbers to get a boolean (#256)
- [x] (bugfix) Added check against null data on `ClickHouseResultSet#getXXX` (#258) (#259)
- [x] (feature) Handle Nothing datatype (#261)
- [x] (bugfix) `ClickHouseConnection#connect` should return null for unaccepted url (#267)
- [x] (enhance) `BalancedClickhouseDataSource` support optional database url
- [x] (test) Added user & password for ClickHouse unit tests (#264)
- [x] (feature) Support arbitrary settings (#268)
- [x] (refactor) Rewrite `StringView` implements `CharSequence` (#270)
- [x] (workflow) Auto report benchmark report.

**Comment by pan3793** [comment]
v2.5.0 has been released on Dec 27, 2020
